### ISSUE TITLE
Running error of ex_top on Elixir 1.1.1

### ISSUE THREAD

**Issue by developerworks** [utkarshkukreti/ex_top#2]
```
➜  ex_top git:(master) ./ex_top         

03:08:12.126 [info]  Protocol: 'inet_tcp': register/listen error: :econnrefused

** (MatchError) no match of right hand side value: {:error, {{:shutdown, {:failed_to_start_child, :net_kernel, {:EXIT, :nodistribution}}}, {:child, :undefined, :net_sup_dynamic, {:erl_distribution, :start_link, [[:ex_top, :shortnames, 15000]]}, :permanent, 1000, :supervisor, [:erl_distribution]}}}
    (ex_top) lib/ex_top.ex:14: ExTop.main/1
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

**Comment by utkarshkukreti** [comment]
According to https://github.com/elixir-lang/elixir/issues/2422, you probably need to start the `epmd` daemon once by running `epmd -daemon`. Does that work?

**Comment by developerworks** [comment]
It works, thanks.
