### ISSUE TITLE
can't connect to local app

### ISSUE THREAD

**Issue by ulutomaz** [utkarshkukreti/ex_top#9]
Hi,

I would like to use ex_top but somehow can't really connect to a running app.

I have (in my project) a name myapp@127.0.0.1 which is quite ok with me. I can see in my var/vm.args a cookie which i use for ex_top command. But then when I launch a command like

./ex_top <with or without node name myapp@127.0.0.1> --cookie='\<string of cookie\>'

First I get 2 options... 
"0". myapp@\<BUT WITH MY HOSTNAME\>

"1". ex_top@\<HOSTNAME\>

I receive an error like....could not connecto to node bla, bla... after picking the 0.
It doesn't really help if i set a nodename with ex_top command. 

Best,
Tomaz

**Comment by utkarshkukreti** [comment]
Hey, could you try giving the ex_top a name with the target app's host, e.g. `ex_top@127.0.0.1`?

    ./ex_top --name ex_top@127.0.0.1 --cookie '<string of cookie>'

That should fix the connection problem I think but you'll then unfortunately run into #8 if you're on Erlang 19. There's a workaround in that issue you can use but I haven't had a chance to find a good solution so I haven't committed it yet.

**Comment by kuroda** [comment]
I got a similar error when I tried to connect a Phoenix server, which is started by this command:


```console
$ elixir --name bar@xaio.local -S mix phx.server
```

Here, `xaio.local` is a hostname.

On another console, I got the following result:

```console
$ ./ex_top
0: bar@xaio
1: ex_top@xaio
0
Could not connect to node bar@xaio with cookie XSG...
```

Taking the utkarshkukreti's advise, I ran this command:

```console
$ ./ex_top --name ex_top@xaio.local
0: bar@xaio.local
1: ex_top@xaio.local
0
```

Then, I got the following error:

```
00:38:18.339 [error] GenServer #PID<0.103.0> terminating
                                                        ** (FunctionClauseError) no function clause matching in Access.get/3
                                                                                                                                (elixir) lib/access.ex:306: Access.get({:badrpc, {:EXIT, {%Protocol.UndefinedError{description: "", protocol: Enumerable, value: :undefined}, [{Enumerable, :impl_for!, 1, [file: '/home/oiax/.kiex/builds/elixir-git/lib/elixir/lib/enum.ex', line: 1]}, {Enumerable, :reduce, 3, [file: '/home/oiax/.kiex/builds/elixir-git/lib/elixir/lib/enum.ex', line: 141]}, {Enum, :sort, 2, [file: 'lib/enum.ex', line: 1919]}, {ExTop.Collector, :collect, 0, [file: 'lib/ex_top/collector.ex', line: 33]}, {:rpc, :"-handle_call_call/6-fun-0-", 5, [file: 'rpc.erl', line: 197]}]}}}, :processes, nil)
                                                                 (ex_top) lib/ex_top.ex:229: ExTop.handle_cast/2
                                                                                                                    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
                                              (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
                                                                                                       (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
                            Last message: {:"$gen_cast", :render}
                                                                 State: %ExTop{data: {:badrpc, {:EXIT, {%Protocol.UndefinedError{description: "", protocol: Enumerable, value: :undefined}, [{Enumerable, :impl_for!, 1, [file: '/home/oiax/.kiex/builds/elixir-git/lib/elixir/lib/enum.ex', line: 1]}, {Enumerable, :reduce, 3, [file: '/home/oiax/.kiex/builds/elixir-git/lib/elixir/lib/enum.ex', line: 141]}, {Enum, :sort, 2, [file: 'lib/enum.ex', line: 1919]}, {ExTop.Collector, :collect, 0, [file: 'lib/ex_top/collector.ex', line: 33]}, {:rpc, :"-handle_call_call/6-fun-0-", 5, [file: 'rpc.erl', line: 197]}]}}}, node: :"bar@xaio.local", offset: 0, paused?: false, rows: 33, schedulers_snapshot: nil, selected: 0, sort_by: :pid, sort_order: :ascending}
                                                                                                      ** (EXIT from #PID<0.91.0>) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Access.get/3
        (elixir) lib/access.ex:306: Access.get({:badrpc, {:EXIT, {%Protocol.UndefinedError{description: "", protocol: Enumerable, value: :undefined}, [{Enumerable, :impl_for!, 1, [file: '/home/oiax/.kiex/builds/elixir-git/lib/elixir/lib/enum.ex', line: 1]}, {Enumerable, :reduce, 3, [file: '/home/oiax/.kiex/builds/elixir-git/lib/elixir/lib/enum.ex', line: 141]}, {Enum, :sort, 2, [file: 'lib/enum.ex', line: 1919]}, {ExTop.Collector, :collect, 0, [file: 'lib/ex_top/collector.ex', line: 33]}, {:rpc, :"-handle_call_call/6-fun-0-", 5, [file: 'rpc.erl', line: 197]}]}}}, :processes, nil)
        (ex_top) lib/ex_top.ex:229: ExTop.handle_cast/2
        (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

My Elixir is 1.6.6 and Erlang/OTP is 21.0.
